project-zot/project-zot.github.io

- next.config.js
Signed-off-by: Raul Kele <raulkeleblk@gmail.com>
> Update next config

- components/Legal.tsx
- styles/Layout.module.scss
Signed-off-by: Amelia-Maria Breda <ameliamaria.breda@dxc.com>
> Updated the link for License and changed Copyright text

- components/Legal.tsx
- components/ProductSection.tsx
- styles/HeroSection.module.scss
- styles/ProductSection.module.scss
Signed-off-by: Raul Kele <raulkeleblk@gmail.com>
> link updates

- .github/workflows/security-scans.yaml
> add security scans github action

- .github/workflows/security-scans.yaml
> fix branch name in security scans

- .github/workflows/security-scans.yaml
> fix token perms for security scan

- components/HeroSection.tsx
- components/ProductSection.tsx
Signed-off-by: Raul Kele <raulkeleblk@gmail.com>
> fix: swapped learn more/ how it works links

- components/Legal.tsx
Signed-off-by: Raul Kele <raulkeleblk@gmail.com>
> fix: Copyright typo fix

- components/HeroSection.tsx
- components/ProductSection.tsx
- package-lock.json
- package.json
Signed-off-by: Amelia-Maria Breda <ambreda@cisco.com>
Closes #20
> Fixed click bug for buttons

- docs/articles/benchmarking-with-zb.md
- material/overrides/main.html
> update benchmark doc

- .github/workflows/commit-msg.yaml
- .github/workflows/dco.yml
- docs/general/architecture.md
- docs/general/whats-new.md
- docs/general/zot-concepts.md
- docs/install-guides/install-guide-k8s.md
- docs/user-guides/user-guide-datapath.md
- material/overrides/home.html
- mkdocs.yml
> docs: cleanup and new sections

- material/overrides/main.html
> docs: revert csp for now

- material/overrides/main.html
> docs: fix go-import meta header

- docs/zot.md
- material/overrides/go-import.html
> docs: fix go-import settings

- index.html
> docs: fix go-import vanity url

- .github/workflows/deploy.yml
- docs/zot.md
- go-import/redirect.html
- material/overrides/go-import.html
- mkdocs.yml
- requirements.txt
> docs: setup redirect for go-imports

- docs/admin-guide/admin-configuration.md
- docs/developer-guide/extensions-dev.md
- docs/developer-guide/onboarding.md
- docs/general/architecture.md
- docs/general/concepts.md
- docs/general/extensions.md
- docs/general/features.md
- docs/general/whats-new.md
- mkdocs.yml
- requirements.txt
Signed-off-by: Michael Shields <mshields@alum.mit.edu>
> added feature and extension topics, removed rev dates, added SVG example

- material/overrides/home.html
> docs: some minor fixes and changes

- mkdocs.yml
Signed-off-by: Michael Shields <mshields@alum.mit.edu>
> docs: added emoji markdown_extension

- mkdocs.yml
- requirements.txt
> docs: minor fixes

- material/overrides/main.html
> docs: modify announcement

- material/overrides/home.html
> docs: some minor cleanup

- mkdocs.yml
> docs: fix the "next" page

- material/overrides/home.html
> docs: update home page msg

- docs/general/features.md
- docs/general/project.md
- material/overrides/home.html
- material/overrides/main.html
- mkdocs.yml
- requirements.txt
> docs: update home page

- docs/general/glossary.md
Signed-off-by: mbshields <mshields@alum.mit.edu>
> added Glossary

- mkdocs.yml
> docs: update footer msg

- mkdocs.yml
> docs: include cncf trademark msg in footer

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/PULL_REQUEST_TEMPLATE.md
> ci: add issue templates

- docs/admin-guide/admin-configuration.md
- docs/articles/authn-authz.md
Signed-off-by: mbshields <mshields@alum.mit.edu>
```release-note
```
> docs: Improve subPath and access policy documentation

- docs/developer-guide/extensions-dev.md
Signed-off-by: Chamseddine Saadoune <saadoune.cham@gmail.com>
Documentation
Little typo fix
> docs: extensions-dev - typo fix

- docs/articles/mirroring.md
- mkdocs.yml
documentation
explains how to configure mirroring
```release-note
```
> docs: add a kb article about setting up zot mirroring

- docs/general/glossary.md
- mkdocs.yml
documentation
none
Updates Glossary topic and adds it to the site navigation
> docs: updated Glossary, added to mkdocs.yml navigation

- docs/articles/mirroring.md
documentation
none
Clarifies behavior in pull-through mirroring mode with polling
> docs: add info about pull-through cache mirroring

- docs/articles/mirroring.md
* docs: add info about pull-through cache mirroring
* docs: add info about pull-through cache mirroring (incorporate comments)
---------
```release-note
```
> docs: add info about pull-through cache mirroring (#81)

- docs/install-guides/install-guide-k8s.md
- docs/install-guides/install-guide-linux.md
- mkdocs.yml
- requirements.txt
Track versioning info in documentation using mkdocs-macros so this happens automatically.
Originally reported by @imjasonh:
https://github.com/project-zot/project-zot.github.io/pull/80
```release-note
```
> docs: fix versioning in documentation with mkdocs-macros

- .github/workflows/spellcheck.yml
- .spellcheck.yaml
> ci: add a spellchecker

- .spellcheck.yaml
- .wordlist.txt
> ci: fix spellchecker config

- docs/admin-guide/admin-configuration.md
- docs/articles/storage.md
documentation
none
adds storage docs changes from PR #78 to the v1.4 branch
> docs: moved storage content to article, added s3 config details

- .github/workflows/spellcheck.yml
> ci: update spellcheck workflow

- .wordlist.txt
- docs/articles/mirroring.md
documentation
none
explains how to use zot mirroring for registry migration or for upgrade/downgrade
> docs: added migration/update to mirroring article

- .wordlist.txt
- docs/admin-guide/admin-configuration.md
- docs/general/extensions.md
documentation
none
documents a new extension:  userprefs
> docs: add userprefs extension

- .wordlist.txt
- docs/articles/kind-deploy.md
- mkdocs.yml
documentation
none
Adds an article for deploying a kind cluster with a zot registry
> docs: added kind deployment article

- .wordlist.txt
- docs/admin-guide/admin-configuration.md
- docs/articles/storage.md
documentation
Adds enhancement to deduplication, with enable/disable at startup
This PR supersedes dev-submitted PR #99
> docs: add startup dedupe

- .wordlist.txt
- docs/general/whats-new.md
documentation
Adds "What's New" for 2.0.0
> docs: add 2.0 features to What's New

- .wordlist.txt
- docs/admin-guide/admin-getting-started.md
- docs/general/releases.md
- docs/general/whats-new.md
documentation
Documents new support for FreeBSD zot binaries
> docs: added FreeBSD binaries support

- .wordlist.txt
- docs/admin-guide/admin-configuration.md
> docs: add scheduler settings in admin guide

- docs/admin-guide/admin-configuration.md
- docs/admin-guide/admin-getting-started.md
- docs/articles/authn-authz.md
- docs/articles/mirroring.md
- docs/articles/monitoring.md
- docs/articles/storage.md
- docs/developer-guide/extensions-dev.md
- docs/developer-guide/onboarding.md
- docs/general/architecture.md
- docs/general/features.md
- docs/general/whats-new.md
- docs/install-guides/install-guide-linux.md
- docs/user-guides/user-guide-datapath.md
documentation bug
Partial fix for issue #117 
The initial commit is a scrub of all broken links, changed to valid links.
The second commit addresses the specific links in issue #117 that were not fixed in the first commit.
Some minor formatting fixes are also included.
> docs: fix broken links in v1.4.3 documentation, other issues in #117

- .wordlist.txt
- docs/admin-guide/admin-configuration.md
- docs/admin-guide/admin-getting-started.md
- docs/articles/authn-authz.md
- docs/articles/kind-deploy.md
- docs/articles/mirroring.md
- docs/articles/monitoring.md
- docs/articles/storage.md
- docs/articles/verifying-signatures.md
- docs/developer-guide/extensions-dev.md
- docs/developer-guide/onboarding.md
- docs/general/architecture.md
- docs/general/extensions.md
- docs/general/features.md
- docs/general/whats-new.md
- docs/install-guides/install-guide-linux.md
- docs/user-guides/user-guide-datapath.md
documentation
Implements several changes from zot PR 1636:
- add trust extension
- new API endpoints for cosign/notation config
- remove mgmt and userprefs extensions from config file
- gc config behavior changes, clarification
- added externalUrl attribute for OpenID behind a proxy or load balancer
> docs: changed signature verification config, minor fixes

- .wordlist.txt
- docs/user-guides/zli.md
documentation
zli syntax updates
> docs: update zli for new 2.0 syntax

- .wordlist.txt
- docs/articles/retention.md
- docs/general/whats-new.md
- mkdocs.yml
> docs: Add retention policies to What's New for 2.0

- .wordlist.txt
- docs/articles/graphql.md
- docs/general/whats-new.md
- mkdocs.yml
> docs: add a GraphQL article

- docs/general/whats-new.md
> docs: add ability to delete tags from UI to What's New

- mkdocs.yml
> docs: move "what's new" higher up the index

- .github/workflows/deploy.yml
- mkdocs.yml
- requirements.txt
> docs: add ability to publish PDF

- mkdocs.yml
> docs: fix top-level mkdocs

- .github/workflows/security.yml
> ci: fix zap scan uri

- .github/workflows/security.yml
> ci: fix zap scan uri (again)

- .wordlist.txt
- docs/general/whats-new.md
> docs: add notes for v2.0.1 release

- go-import/redirect.html
> fix: go-import path moved to zotregistry.dev

- mkdocs.yml
https://github.com/project-zot/project-zot.github.io/issues/152
```release-note
```
> fix: trademark link is broken

- docs/install-guides/install-guide-k8s.md
documentation
Adds info about a new helm value `strategy.type`. 
Adds very basic info about this change https://github.com/project-zot/helm-charts/pull/38 hopefully comming to the helm-charts repo.  This PR is dependent on the merge of the PR above.
```release-note
```
> docs: Add info about helm value deployment strategy type.

- material/overrides/main.html
> docs: fix urls to point to zotregistry.dev

- material/overrides/home.html
fixes https://github.com/project-zot/project-zot.github.io/issues/166
> fix(links): fix zotregistry.io redirection from the home page

- docs/general/whats-new.md
> docs: update "whats new" with v2.0.3 release

- docs/general/whats-new.md
> docs: update "whats new" with v2.0.4 release

- docs/general/whats-new.md
We are now cutting release candidates for v2.1.0.
Documentation needs to be updated.
```release-note
```
> docs: update "whats new" for v2.1.0 release train

- docs/general/whats-new.md
> docs: v2.1.0 release docs

- docs/general/whats-new.md
> docs: remove "release-candidate" text

- docs/user-guides/user-guide-datapath.md
> docs: update oras documentation to attach a reference

- docs/admin-guide/admin-configuration.md
- docs/general/whats-new.md
> docs: some doc improvements

- docs/articles/storage.md
documentation
#189
It will save folks time attempting to get multiple replicas working with local filesystem.
Viewed file to ensure proper formatting
N/A
No
No - other than a minor documentation addition.
```release-note
```
> Boltdb doesn't support multiple instances against same db with local filesystem

- docs/articles/containerd.md
- mkdocs.yml
Add a small article to show example configuration
```release-note
```
> docs: containerd can mirror from zot

- docs/articles/retention.md
Resolves https://github.com/project-zot/zot/issues/2867
> fix: more detailed explanation and examples for retention policies

- .wordlist.txt
- docs/articles/containerd.md
- docs/general/whats-new.md
mirror config has changed for containerd 2.x
```release-note
```
> docs: add mirror config for containerd v2.x

- mkdocs.yml
…thub.com>
Right year update
Rights year update
```release-note
```
> All rights year update

- .wordlist.txt
- docs/articles/authn-authz.md
- docs/articles/monitoring.md
resolves: https://github.com/project-zot/project-zot.github.io/issues/199
resolves: https://github.com/project-zot/zot/issues/3142
adds documentation for: https://github.com/project-zot/zot/pull/2927
> Enhance documentation for authorization

- docs/articles/authn-authz.md
- docs/install-guides/install-guide-linux.md
Fixes [#3158](https://github.com/project-zot/zot/issues/3158)
> doc: remove obsolete configuration options

- .spellcheck.yaml
- .wordlist.txt
- docs/articles/events.md
- docs/articles/mirroring.md
- docs/articles/storage.md
- docs/general/whats-new.md
> docs: add event support documentation and AWS ECR sync example

- docs/general/whats-new.md
> docs: fix link

- docs/articles/authn-authz.md
documentation
Part of https://github.com/project-zot/zot/issues/3173, see https://github.com/project-zot/zot/issues/3173#issuecomment-2928079897 for more info.
```release-note
```
> docs: update bearer auth docs to clarify supported public key formats

- docs/general/whats-new.md
> docs: v2.1.4

- docs/articles/authn-authz.md
documentation
https://github.com/project-zot/project-zot.github.io/issues/210
This PR documents the changes introduced with https://github.com/project-zot/zot/pull/3244 which allows to put oidc credentials in a separate file.
> feat: document oidc credentials file

- docs/general/whats-new.md
> docs: v2.1.8
