project-zot/project-zot.github.io

docs/articles/monitoring.md

documentation
none
removes benchmarking section from Monitoring article because there is already a separate Benchmarking article

docs: removed zb section from Monitoring article

---

docs/install-guides/install-guide-k8s.md
docs/install-guides/install-guide-linux.md
mkdocs.yml
requirements.txt

Track versioning info in documentation using mkdocs-macros so this happens automatically.
Originally reported by @imjasonh:
https://github.com/project-zot/project-zot.github.io/pull/80
(cherry picked from commit e87d28307905b546dc186fc142c97de159f143f0)
```release-note
```

docs: fix versioning in documentation with mkdocs-macros

---

docs/articles/authn-authz.md

documentation
For v1.4, explains that bcrypt is hashing function for htpasswd
Similar to PR #106 for v2.0.0

docs: add note about bcrypt for htpasswd

---

.wordlist.txt
docs/articles/verifying-signatures.md
mkdocs.yml

documentation
none
Adds article explaining how zot verifies image signatures.
This PR is an edit of Andreea's PR:  "docs: add info about verifying signatures #96"

docs: add Verifying Image Signatures article

---

.wordlist.txt
docs/articles/authn-authz.md

documentation
Adds ability to define groups for authz policies
This PR supersedes previous PR https://github.com/project-zot/project-zot.github.io/pull/109

docs: add group policies for user auth (replaces 109)

---

.wordlist.txt
docs/developer-guide/onboarding.md

documentation
none
Provides a general explanation of where and how repo data and process data is stored in zot memory, including database names and paths.

docs: added 'Data storage locations in zot' to Developer Guide

---

.wordlist.txt
docs/articles/workflow.md
docs/general/whats-new.md
mkdocs.yml

documentation
none
Demonstrates an end-to-end workflow for installing a zot registry, pushing and signing an image and artifact, and verifying the results.

docs: new article for demonstrating zot workflow with artifacts

---

.wordlist.txt
docs/articles/retention.md
mkdocs.yml

documentation
[Feat]: Document the retention policy configuration #129

docs: add article for Retention Policies

---

docs/articles/authn-authz.md
docs/general/whats-new.md

docs: LDAP separate credentials file

---

.wordlist.txt
docs/developer-guide/api-user-guide.md
docs/general/whats-new.md

documentation
- adds description of new digest search in What's New
- fixes a broken link in Using the API

docs: add digest search to What's New

---

.github/workflows/ci.yml
.github/workflows/deploy.yml

So that dependencies don't break.
```release-note
```

ci: pin python version to 3.11

---

docs/articles/authn-authz.md

Fix for https://github.com/project-zot/zot/issues/2191
Callback URL syntax path is incorrect, misses the `zot/`.  Correct path is given in: https://github.com/project-zot/zot/blob/9def35f3b8b38f5a438146a09087edcec00537c7/examples/README.md?plain=1#L294
documentation
Fix for https://github.com/project-zot/zot/issues/2191
Callback URL is incorrect in docs.

correct the callback url

---

docs/install-guides/install-guide-k8s.md
docs/install-guides/install-guide-linux.md

documentation
I have added some missing steps in the installation.
Fixes minor formatting issues.
No.
Just documentation updates, added missing steps.

fix: update docs for linux install

---

docs/articles/immutable-tags.md

Fixes https://github.com/project-zot/project-zot.github.io/issues/160
```release-note
```

docs: add an article for "immutable image tags"

---

.wordlist.txt
docs/general/whats-new.md
docs/user-guides/zli.md

Add a summary of important changes in release v2.0.2
```release-note
```

docs: update whats-new section for v2.0.2

---

mkdocs.yml

Fixes #164
#164 
Easier to find content without searching
```release-note
```

docs: add Immutable Tags article

---

.wordlist.txt
docs/articles/high-availability.md
mkdocs.yml

docs: add high availability article

---

docs/articles/mirroring.md

documentation
add a warning to prevent misunderstanding of the OCI registry mirror
see: https://github.com/project-zot/zot/issues/2584
```release-note
```

Add warning about pull with digest

---

material/overrides/home.html
requirements.txt

chore: fix dependabot alerts

---

docs/admin-guide/admin-configuration.md
docs/general/whats-new.md

documentation
A new configuration setting allows you to store images using the schema [Docker Manifest v2 Schema v2](https://distribution.github.io/distribution/spec/manifest-v2-2/). With this setting enabled, zot makes no modifications to the image's manifest or digest. Such modifications would otherwise break the image's signature and attestations.

docs: added config for docker2s2, plus  What's New for v2.1.2

---

.wordlist.txt
docs/articles/clustering.md
docs/articles/storage.md

doc: document Redis support

---

docs/articles/storage.md

`DeleteTable` is theoretically only needed to run the tests.

fix: Update AWS DynamoDB permission list, and DynamoDB table names

---

docs/articles/retention.md

fix: replace repoNames with repositories in docs/articles/retention.md
